### ISSUE TITLE
Backup directly to file

### ISSUE THREAD

**Issue by oawd** [SecUSo/privacy-friendly-backup#28]
Currently a backup is first loaded into the cloud and can afterwards be exported into a file.
I would prefer to only backup into a file on the device.

**Comment by udenr** [comment]
Currently, the backup is actually never uploaded to a cloud provider. It is a bit of a misleading image, as we had planned to support backups in the cloud in the future. However, this has not happened yet.
The backups are stored within the app / on the local storage of the device and the export function allows you to export them from the app.
