### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [SecUSo/privacy-friendly-backup#34]
https://monitor.f-droid.org/builds/log/org.secuso.privacyfriendlybackup/7#site-footer

Is the BackupAPI really not updated for the last 5 months? https://github.com/SecUSo/privacy-friendly-backup/tree/v1.3.3

I see a new tag 2 weeks ago https://github.com/SecUSo/privacy-friendly-backup-api/releases/tag/v1.4.0

**Comment by udenr** [comment]
Do you still remember what the issue was, because I can only see the successful build in the log you provided?

We will update to API version 1.4.0 in the next version.

**Comment by licaon-kter** [comment]
No idea now :shrug: 

Glad it's ok
