### ISSUE TITLE
App does not display all other apps

### ISSUE THREAD

**Issue by HersirX** [SecUSo/privacy-friendly-backup#4]
Hi
I am currently using Notes and Tasks. For Notes I can perform a backup, but not for tasks.
Any ideas why?
Further, why not list the current address of the project https://secuso.aifb.kit.edu/105.php? 
Some browsers block the connection to secuso.org, as it redirects somewhere differently.

![image](https://user-images.githubusercontent.com/77176169/135744630-ba025290-93ab-407c-9c9f-5f9b440ba90b.png)

Many thanks

**Comment by Kamuno** [comment]
Changed the link.
We will add a list of Applications that should work with the backup app to the readme file in the repostiory.

It takes a lot more time than anticipated to integrate every privacy friendly app with the backup app.
So some apps will work and some will not yet. But we are in the process of including every app.

Now and in the coming months we have a little bit more support with the development of the apps so integration will hopefully speed up a bit.
