### ISSUE TITLE
Incorrect app was referenced on the KIT information page for the app

### ISSUE THREAD

**Issue by Lukas2112** [SecUSo/privacy-friendly-backup#6]
It seems 
![privacyfriendlybackupwrongapp](https://user-images.githubusercontent.com/47597136/139495771-73283071-4097-43b1-ab2e-b87da3011db6.png)
that a wrong app was referenced in the info page on kit.edu when backing up (see attachment).

**Comment by Kamuno** [comment]
Thanks. This should be fixed as well.
